-- Inventory Stock Room: run this in the Supabase SQL Editor for ST.
-- Safe to run more than once. The web Stock Room reads and writes public.inventory.

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  product_id bigint,
  sku text,
  stock_qty integer not null default 0,
  stock_status text not null default 'OUT_OF_STOCK',
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.inventory add column if not exists product_id bigint;
alter table public.inventory add column if not exists sku text;
alter table public.inventory add column if not exists stock_qty integer not null default 0;
alter table public.inventory add column if not exists stock_status text not null default 'OUT_OF_STOCK';
alter table public.inventory add column if not exists updated_at timestamptz not null default now();
alter table public.inventory add column if not exists created_at timestamptz not null default now();

alter table public.inventory drop constraint if exists inventory_stock_status_check;
alter table public.inventory add constraint inventory_stock_status_check check (stock_status in ('IN_STOCK', 'OUT_OF_STOCK'));
alter table public.inventory drop constraint if exists inventory_stock_qty_nonnegative;
alter table public.inventory add constraint inventory_stock_qty_nonnegative check (stock_qty >= 0);

create unique index if not exists inventory_product_id_uidx on public.inventory (product_id) where product_id is not null;
create unique index if not exists inventory_sku_uidx on public.inventory (lower(trim(sku))) where sku is not null and trim(sku) <> '';
create index if not exists inventory_status_idx on public.inventory (stock_status);

create or replace function public.inventory_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  new.stock_qty = greatest(coalesce(new.stock_qty, 0), 0);
  new.stock_status = case when new.stock_qty > 0 then 'IN_STOCK' else 'OUT_OF_STOCK' end;
  return new;
end;
$$;

drop trigger if exists inventory_set_updated_at_trigger on public.inventory;
create trigger inventory_set_updated_at_trigger
before insert or update on public.inventory
for each row execute function public.inventory_set_updated_at();

create or replace view public.vw_stock_room as
select
  pm.id as product_id,
  pm.sku,
  coalesce(pm.th_name, pm.product_name, pm.name_standard, pm.label_display, pm.sku) as product_name,
  coalesce(pm.label_display, pm.display_for_packer, pm.name_standard, pm.product_name, pm.sku) as display_master,
  coalesce(pm.unit_price, pm.price, pm.cod_default) as unit_price,
  coalesce(i.stock_qty, 0) as stock_qty,
  case when coalesce(i.stock_qty, 0) > 0 then 'IN_STOCK' else 'OUT_OF_STOCK' end as stock_status,
  i.updated_at
from public.product_master pm
left join public.inventory i on i.product_id = pm.id or lower(trim(i.sku)) = lower(trim(pm.sku));

-- Browser access used by the existing Stock Room page.
-- If the project already has stricter security policies, keep those policies instead.
alter table public.inventory enable row level security;
drop policy if exists inventory_stock_room_read on public.inventory;
drop policy if exists inventory_stock_room_write on public.inventory;
create policy inventory_stock_room_read on public.inventory for select to anon, authenticated using (true);
create policy inventory_stock_room_write on public.inventory for insert to anon, authenticated with check (true);
create policy inventory_stock_room_update on public.inventory for update to anon, authenticated using (true) with check (true);

-- Optional helper for SQL/manual testing:
-- select * from public.vw_stock_room order by sku;
