-- =====================================================================
-- SUPHABASS FOUNDATION PLATFORM 001
-- Additive only: create missing tables/columns, never drop or rewrite data.
-- Run this before installing the v16 pipeline trigger.
-- =====================================================================

begin;

-- [1] CENTRAL MASTER: add only columns required by the engines and rooms.
alter table if exists public.central_order_master
  add column if not exists tracking_number text,
  add column if not exists phone_number text,
  add column if not exists built_bill_text text,
  add column if not exists routing_destination text,
  add column if not exists warning_tag text,
  add column if not exists repair_log text,
  add column if not exists final_display_for_packer text,
  add column if not exists address_display_packer text,
  add column if not exists stock_status text,
  add column if not exists is_out_of_stock boolean default false,
  add column if not exists is_ready_to_pack boolean default false,
  add column if not exists telegram_status text default 'PENDING',
  add column if not exists telegram_body text,
  add column if not exists cod_check_status text,
  add column if not exists mapping_status text,
  add column if not exists audit_status text,
  add column if not exists audit_flags text,
  add column if not exists alert_code text,
  add column if not exists alert_codes jsonb,
  add column if not exists alert_priority integer,
  add column if not exists missing_fields jsonb,
  add column if not exists address_confidence_score integer,
  add column if not exists address_match_status text,
  add column if not exists district_code text,
  add column if not exists amphoe_code text,
  add column if not exists province_code text,
  add column if not exists source_text text,
  add column if not exists source_payload jsonb,
  add column if not exists payload_snapshot jsonb;

-- [2] PRODUCT MASTER: create only when absent. Existing table is untouched.
create table if not exists public.product_master (
  id bigint generated by default as identity primary key,
  sku text,
  th_name text,
  name_standard text,
  product_name text,
  alias text,
  emoji text,
  display_for_packer text,
  label_display text,
  unit_price numeric,
  stock_qty numeric default 0,
  stock_status text default 'UNKNOWN',
  status text default 'ACTIVE',
  out_of_stock_joke text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists product_master_sku_idx on public.product_master (sku);

-- [3] THAI ADDRESS MASTER: zipcode-first address repair source.
create table if not exists public.thailand_address_master (
  id bigint generated by default as identity primary key,
  zipcode text not null,
  district text,
  amphoe text,
  province text,
  district_code text,
  amphoe_code text,
  province_code text,
  created_at timestamptz default now(),
  unique (zipcode, district, amphoe, province)
);
create index if not exists thailand_address_master_zipcode_idx
  on public.thailand_address_master (zipcode);

-- [4] PARCELS: optional tracking lookup by normalized phone + COD.
create table if not exists public.parcels (
  id bigint generated by default as identity primary key,
  tracking_number text,
  phone_number text,
  cod_amount numeric,
  carrier text,
  parcel_status text,
  order_number text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists parcels_phone_number_idx on public.parcels (phone_number);
create index if not exists parcels_tracking_number_idx on public.parcels (tracking_number);

-- [5] CUSTOMER BLACKLIST: optional audit lookup; absence never blocks ingestion.
create table if not exists public.customer_blacklist (
  id bigint generated by default as identity primary key,
  phone text,
  phone_norm text,
  customer_name text,
  reason text,
  status text default 'ACTIVE',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists customer_blacklist_phone_norm_idx
  on public.customer_blacklist (phone_norm);

-- [6] ROOM LINK VIEW: one row, many rooms; source remains central_order_master.
create or replace view public.vw_order_room_links as
select
  com.id,
  com.order_number,
  com.customer_name,
  com.facebook_name,
  com.phone,
  com.full_address,
  com.cod_amount,
  com.order_status,
  com.mapping_status,
  com.stock_status,
  com.telegram_status,
  com.routing_destination,
  com.warning_tag,
  com.repair_log,
  com.tracking_number,
  com.is_ready_to_pack,
  com.address_confidence_score,
  com.address_match_status,
  com.sniper_x_text_clean,
  com.clean_text,
  com.chat_timeline,
  com.full_chunk_text,
  com.source_text,
  com.source_payload,
  com.payload_snapshot,
  case
    when upper(coalesce(com.telegram_status, '')) = 'SENT' then 'SENT_ROOM'
    when coalesce(com.routing_destination, '') = 'QUARANTINE_24H' then 'REPAIR_ROOM'
    when upper(coalesce(com.stock_status, '')) like '%OUT%' or coalesce(com.is_out_of_stock, false) then 'OUT_OF_STOCK_ROOM'
    when upper(coalesce(com.mapping_status, '')) in ('UNMATCHED', 'REVIEW', 'CHECK_DATA') then 'PRODUCT_REVIEW_ROOM'
    when com.tracking_number is not null and trim(com.tracking_number) <> '' then 'TRACKING_ROOM'
    when upper(coalesce(com.order_status, '')) = 'CLEAN' then 'NORMAL_ORDER_ROOM'
    else 'INBOX_ROOM'
  end as room_key,
  case
    when upper(coalesce(com.telegram_status, '')) = 'SENT' then '📨 SENT'
    when coalesce(com.routing_destination, '') = 'QUARANTINE_24H' then '🛠️ REPAIR'
    when upper(coalesce(com.stock_status, '')) like '%OUT%' or coalesce(com.is_out_of_stock, false) then '❌ OUT_OF_STOCK'
    when upper(coalesce(com.mapping_status, '')) in ('UNMATCHED', 'REVIEW', 'CHECK_DATA') then '🧩 PRODUCT_REVIEW'
    when com.tracking_number is not null and trim(com.tracking_number) <> '' then '📦 TRACKING_READY'
    when upper(coalesce(com.order_status, '')) = 'CLEAN' then '✅ READY'
    else '📥 INBOX'
  end as status_label
from public.central_order_master com;

-- [7] TELEGRAM OUTPUT VIEW: output only; never mutates evidence.
create or replace view public.vw_out_telegram as
select
  r.*,
  coalesce(nullif(r.built_bill_text, ''), nullif(r.telegram_body, ''), r.clean_text) as telegram_output_text
from public.vw_order_room_links r;

notify pgrst, 'reload schema';
commit;

-- Important: install the v16 trigger only after this foundation succeeds.
-- The v16 trigger must preserve clean_text and write generated text to built_bill_text.
