-- SUPHABASS canonical order schema migration (safe, idempotent)
-- Apply in Supabase SQL Editor with the service-role migration workflow.
-- The browser must use only the anon key and read vw_orders_web_all_fields.

create table if not exists public.canonical_orders (
  id bigint generated by default as identity primary key,
  desk_key text not null default 'suphabass',
  source_system text not null default 'suphabass',
  upsert_key text not null,
  order_number text,
  order_time timestamptz,
  order_date date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  page_id text,
  page_name text,
  thread_id text,
  conversation_key text,
  customer_id text,
  customer_name text,
  phone text,
  full_address text,
  address_display_packer text,
  district text,
  amphoe text,
  province text,
  zipcode text,
  cod_amount numeric,
  raw_cod_amount numeric,
  expected_cod numeric,
  raw_text_with_phone_timed text,
  source_text text,
  sniper_x_text_clean text,
  clean_text text,
  single_cleaned_block text,
  chat_timeline jsonb not null default '[]'::jsonb,
  source_payload jsonb not null default '{}'::jsonb,
  order_items jsonb not null default '[]'::jsonb,
  items_json jsonb not null default '[]'::jsonb,
  items_text text,
  items_count integer not null default 0,
  total_quantity numeric not null default 0,
  mapping_status text,
  audit_status text,
  order_status text,
  is_ready_to_pack boolean not null default false,
  telegram_status text
);

create unique index if not exists canonical_orders_suphabass_upsert_key_idx on public.canonical_orders (upsert_key);
create index if not exists canonical_orders_suphabass_page_thread_idx on public.canonical_orders (desk_key, page_id, thread_id, created_at desc);

create table if not exists public.canonical_order_items (
  order_id bigint not null references public.canonical_orders(id) on delete cascade,
  line_no integer not null,
  sku text,
  product_id text,
  product_name text,
  th_name text,
  label_display text,
  display_for_packer text,
  raw_product_text text not null,
  raw_product_text_norm text,
  raw_item_text text,
  quantity numeric not null default 1,
  extracted_qty numeric,
  unit_price numeric,
  expected_cod numeric,
  mapping_status text not null default 'REVIEW',
  match_confidence numeric,
  match_method text,
  candidate_skus jsonb not null default '[]'::jsonb,
  source_payload_item jsonb not null default '{}'::jsonb,
  primary key (order_id, line_no)
);

comment on table public.canonical_orders is 'SUPHABASS canonical order header and evidence hub';
comment on table public.canonical_order_items is 'Idempotent child item rows keyed by order_id,line_no';

-- If the project already owns vw_orders_web_all_fields, keep that view and expose
-- desk_key/source_payload/raw_text_with_phone_timed/order item fallback fields there.
-- Do not put service-role keys in browser code.
