-- TELEGRAM SEND ROOM / ORDER_ITEMS SOURCE OF TRUTH
-- Run after SUPHABASS-FULL-SCHEMA-001-009.sql.
-- Deterministic parsing/building belongs in n8n; Supabase stores the clean result,
-- child order lines, send state, and append-only delivery history.

alter table public.central_order_master
  add column if not exists telegram_status text not null default 'PENDING',
  add column if not exists telegram_chat_id text,
  add column if not exists telegram_message text,
  add column if not exists telegram_parse_mode text default 'HTML',
  add column if not exists telegram_send_key text,
  add column if not exists telegram_sent_at timestamptz,
  add column if not exists telegram_message_id text,
  add column if not exists telegram_last_error text;

create unique index if not exists central_order_master_telegram_send_key_uidx
  on public.central_order_master (telegram_send_key)
  where telegram_send_key is not null;

create index if not exists central_order_master_telegram_queue_idx
  on public.central_order_master (telegram_status, created_at desc);

-- The send room reads product lines from canonical_order_items first.
-- The JSON fallback keeps old rows usable while the child table is being backfilled.
create or replace view public.vw_telegram_send_room as
select
  o.id,
  o.upsert_key,
  o.order_number,
  o.order_time,
  o.page_id,
  o.page_name,
  o.customer_name,
  o.phone,
  o.full_address,
  o.address_display_packer,
  o.zipcode,
  o.cod_amount,
  o.raw_cod_amount,
  o.expected_cod,
  o.order_status,
  o.telegram_status,
  o.telegram_chat_id,
  o.telegram_message,
  o.telegram_parse_mode,
  o.telegram_send_key,
  coalesce(
    jsonb_agg(jsonb_build_object(
      'line_no', i.line_no,
      'sku', i.sku,
      'product_id', i.product_id,
      'product_name', i.product_name,
      'th_name', i.th_name,
      'label_display', i.label_display,
      'display_for_packer', i.display_for_packer,
      'raw_product_text', i.raw_product_text,
      'quantity', i.quantity,
      'unit_price', i.unit_price,
      'mapping_status', i.mapping_status
    ) order by i.line_no) filter (where i.order_id is not null),
    nullif(o.order_items, '[]'::jsonb),
    '[]'::jsonb
  ) as order_items,
  count(i.order_id)::integer as child_item_count
from public.central_order_master o
left join public.canonical_order_items i on i.order_id = o.id
group by o.id;

-- Queue only complete, not-yet-sent bills. Do not mark SENT here.
create or replace view public.vw_telegram_send_queue as
select *
from public.vw_telegram_send_room
where telegram_status in ('READY_TO_SEND', 'RETRY')
  and coalesce(telegram_message, '') <> ''
  and coalesce(telegram_sent_at is null, true);

-- Idempotent archive. n8n should upsert this row after Telegram succeeds.
create table if not exists public.telegram_send_archive (
  id bigint generated by default as identity primary key,
  send_key text not null unique,
  order_id bigint not null,
  order_number text,
  telegram_chat_id text not null,
  telegram_message_id text,
  telegram_text text not null,
  telegram_payload jsonb not null default '{}'::jsonb,
  sent_at timestamptz not null default now(),
  send_result jsonb not null default '{}'::jsonb
);
create index if not exists telegram_send_archive_order_idx
  on public.telegram_send_archive (order_id, sent_at desc);

-- n8n status transitions (use REST PATCH with the order id):
-- READY_TO_SEND -> SENDING -> SENT
-- any Telegram error -> RETRY and telegram_last_error = error text
-- missing/unmapped order_items -> REVIEW (never send automatically)

notify pgrst, 'reload schema';
