import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { clearSupabaseConfig, getSupabase, getSupabaseConfig, saveSupabaseConfig } from "@/lib/canonical";
import { CheckCircle2, Database, Loader2, XCircle } from "lucide-react";

export default function ConnectSupabase() {
  const [, navigate] = useLocation();
  const existing = getSupabaseConfig();
  const [url, setUrl] = useState(existing?.url || "");
  const [anonKey, setAnonKey] = useState(existing?.anonKey || "");
  const [table, setTable] = useState(existing?.orderTable || "central_order_master");
  const [status, setStatus] = useState<"idle" | "testing" | "ok" | "error">("idle");
  const [message, setMessage] = useState("");
  const test = async () => { setStatus("testing"); setMessage(""); try { const cleanUrl = url.trim().replace(/\/$/, ""); const cleanKey = anonKey.trim(); if (!/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(cleanUrl)) throw new Error("Supabase URL ต้องเป็นรูปแบบ https://ชื่อโปรเจกต์.supabase.co"); if (!cleanKey) throw new Error("กรุณาวาง Anon/Publishable Key ก่อน"); if (/service_role|secret/i.test(cleanKey)) throw new Error("ห้ามใช้ service-role หรือ secret key ในหน้าเว็บ ให้ใช้ Anon/Publishable Key"); saveSupabaseConfig({ url: cleanUrl, anonKey: cleanKey, orderTable: table }); const api = getSupabase(); if (!api) throw new Error("สร้าง Supabase client ไม่สำเร็จ"); const { count, error } = await api.from(table.trim() || "central_order_master").select("id", { count: "exact", head: true }); if (error) throw error; setStatus("ok"); setMessage(`เชื่อมสำเร็จ · ${count ?? 0} แถวใน ${table.trim() || "central_order_master"}`); } catch (error) { setStatus("error"); setMessage(error instanceof Error ? error.message : String(error)); } };
  useEffect(() => { if (status === "ok") { const timer = window.setTimeout(() => navigate("/orders"), 1000); return () => window.clearTimeout(timer); } }, [status, navigate]);
  return <div className="flex min-h-[calc(100vh-2rem)] items-center justify-center p-4"><Card className="w-full max-w-xl rounded-3xl border-cyan-400/20 bg-[#100c19] cyber-glow"><CardHeader><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.25em] text-cyan-300"><Database className="h-4 w-4" /> MANUS3 · CONNECT</div><CardTitle className="text-2xl text-white">เชื่อมต่อฐานของค่ายนี้</CardTitle><p className="text-sm leading-6 text-violet-100/55">ค่าจะเก็บไว้ใน localStorage ของ browser เครื่องนี้เท่านั้น ใช้ Anon/Publishable Key เท่านั้น</p></CardHeader><CardContent className="space-y-4"><label className="block text-xs text-violet-100/60">SUPABASE URL<Input value={url} onChange={e => setUrl(e.target.value)} placeholder="https://your-project.supabase.co" className="mt-1 border-cyan-400/20 bg-black/30 text-white" /></label><label className="block text-xs text-violet-100/60">SUPABASE ANON KEY<textarea value={anonKey} onChange={e => setAnonKey(e.target.value)} placeholder="eyJ... หรือ sb_publishable_..." className="mt-1 min-h-28 w-full rounded-xl border border-cyan-400/20 bg-black/30 p-3 font-mono text-xs text-white outline-none focus:ring-2 focus:ring-cyan-400/20" /></label><label className="block text-xs text-violet-100/60">TABLE NAME<Input value={table} onChange={e => setTable(e.target.value)} className="mt-1 border-cyan-400/20 bg-black/30 font-mono text-white" /></label><div className="grid gap-2 sm:grid-cols-2"><Button onClick={test} disabled={status === "testing"} className="w-full bg-gradient-to-r from-cyan-500 to-fuchsia-600 text-white">{status === "testing" ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Database className="mr-2 h-4 w-4" />}เชื่อมต่อและทดสอบ</Button><Button type="button" variant="outline" onClick={() => { clearSupabaseConfig(); setUrl(""); setAnonKey(""); setStatus("idle"); setMessage("ล้างค่าฐานเดิมแล้ว"); }} className="w-full border-red-400/20 bg-red-400/5 text-red-200">ล้างค่าฐานเดิม</Button></div>{status !== "idle" && <div className={`flex items-start gap-2 rounded-xl border p-3 text-sm ${status === "ok" ? "border-emerald-400/25 bg-emerald-400/10 text-emerald-200" : status === "error" ? "border-red-400/25 bg-red-400/10 text-red-200" : "border-cyan-400/20 bg-cyan-400/10 text-cyan-200"}`}>{status === "ok" ? <CheckCircle2 className="mt-0.5 h-4 w-4" /> : status === "error" ? <XCircle className="mt-0.5 h-4 w-4" /> : <Loader2 className="mt-0.5 h-4 w-4 animate-spin" />}<span>{status === "testing" ? "กำลังทดสอบการอ่านตาราง…" : message}</span></div>}</CardContent></Card></div>;
}
