import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, RefreshCw, ShieldCheck } from "lucide-react";

export default function ProductAlienMap() {
  const reviews = trpc.productAlien.reviews.useQuery(undefined, { refetchInterval: 30_000 });
  const rows = (reviews.data ?? []) as Array<Record<string, unknown>>;
  return <div className="min-h-full space-y-5 text-white">
    <header className="rounded-3xl border border-orange-400/20 bg-[#100c19] p-6 shadow-2xl"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.24em] text-orange-300"><ShieldCheck className="mr-2 inline h-4 w-4" />PRODUCT ALIEN · MAP REVIEW</p><h1 className="mt-3 text-3xl font-semibold">ห้อง Alien แมป</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-orange-100/55">ตรวจ raw เป็นหลักฐานสูงสุด เทียบ SKU/จำนวน และอ่าน Master Display ที่มีอยู่แล้วเท่านั้น ห้ามเว็บสร้าง Master ใหม่</p></div><Button variant="outline" onClick={() => reviews.refetch()} className="border-orange-400/20 bg-transparent text-orange-100"><RefreshCw className={reviews.isFetching ? "mr-2 h-4 w-4 animate-spin" : "mr-2 h-4 w-4"} />รีเฟรช</Button></div></header>
    <Card className="rounded-3xl border-orange-400/15 bg-[#100d15]"><CardHeader><CardTitle className="text-base">คิวตรวจผลแมป</CardTitle></CardHeader><CardContent className="space-y-3">{reviews.isLoading ? <p className="p-8 text-center text-sm text-orange-100/40">กำลังโหลด…</p> : rows.map((row, index) => { const raw = String(row.raw_text ?? ""); const master = String(row.master_display_for_packer ?? ""); const status = String(row.mapping_status ?? "REVIEW"); const conflict = !master || status !== "MATCHED"; return <div key={String(row.id ?? index)} className={`rounded-2xl border p-4 ${conflict ? "border-amber-400/25 bg-amber-400/[0.04]" : "border-emerald-400/20 bg-emerald-400/[0.03]"}`}><div className="flex flex-wrap items-center gap-2"><Badge className={conflict ? "border-amber-400/20 bg-amber-400/10 text-amber-200" : "border-emerald-400/20 bg-emerald-400/10 text-emerald-200"}>{conflict ? "NEEDS_REVIEW" : "MATCHED"}</Badge><span className="font-mono text-xs text-orange-100/55">{String(row.order_number ?? row.upsert_key ?? "")}</span><span className="text-xs text-orange-100/45">{String(row.page_name ?? "")}</span></div><div className="mt-3 grid gap-3 lg:grid-cols-2"><div className="rounded-xl border border-red-400/15 bg-red-400/[0.04] p-3"><p className="text-[10px] uppercase tracking-[0.2em] text-red-200">RAW SOURCE — เชื่อค่านี้</p><p className="mt-2 whitespace-pre-wrap break-words font-mono text-sm text-white">{raw || "ไม่มี raw_text"}</p></div><div className="rounded-xl border border-orange-400/15 bg-orange-400/[0.04] p-3"><p className="text-[10px] uppercase tracking-[0.2em] text-orange-200">MASTER DISPLAY — อ่านอย่างเดียว</p><p className="mt-2 whitespace-pre-wrap break-words text-sm text-orange-50">{master || "ยังไม่มี Master Display"}</p><p className="mt-2 text-xs text-orange-100/45">SKU: {String(row.observed_sku ?? "—")} · product_id: {String(row.observed_product_id ?? "—")} · จำนวนจาก alias: {String(row.quantity_from_alias ?? "—")}</p></div></div><div className="mt-3 flex items-center gap-2 text-xs text-orange-100/55">{conflict ? <AlertTriangle className="h-4 w-4 text-amber-300" /> : <CheckCircle2 className="h-4 w-4 text-emerald-300" />} raw/alias/จำนวนต้องไม่ถูกผลปลายทางเขียนทับ</div></div> })}{!reviews.isLoading && !rows.length ? <p className="p-8 text-center text-sm text-orange-100/40">ยังไม่มีรายการในคิวแมป</p> : null}</CardContent></Card>
  </div>;
}
