-- Product Alien rooms: simple raw evidence storage + mapping review queue
-- Read-only sources: product_master, product_map_master
-- This migration never updates either master table.

create table if not exists public.product_alien_terms (
  id bigint generated by default as identity primary key,
  upsert_key text,
  facebook_name text,
  thread_id text,
  page_id text,
  page_name text,
  order_time_display text,
  order_number text,
  customer_id text,
  cod text,
  chattime text,
  message_id text,
  line_no integer,
  raw_text text not null,
  raw_text_full text,
  alias_text text,
  alias_norm text,
  alias_tokens text,
  alias_quantity_text text,
  quantity_from_alias text,
  quantity_source text not null default 'ALIAS_TEXT',
  source text not null default 'CAPTURED_FROM_ORDER',
  source_logic text,
  product_id text,
  sku text,
  quantity text,
  qty text,
  extracted_qty text,
  unit text,
  mapping_status text not null default 'REVIEW',
  review_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_alien_map_reviews (
  id bigint generated by default as identity primary key,
  alien_term_id bigint not null references public.product_alien_terms(id) on delete cascade,
  upsert_key text,
  thread_id text,
  page_id text,
  page_name text,
  order_number text,
  customer_id text,
  raw_text text not null,
  alias_text text,
  alias_norm text,
  alias_quantity_text text,
  quantity_from_alias text,
  observed_sku text,
  observed_product_id text,
  observed_quantity text,
  master_display_for_packer text,
  mapping_status text not null default 'REVIEW',
  review_reason text,
  reviewer_note text,
  reviewed_by text,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists product_alien_terms_order_idx on public.product_alien_terms (order_number, line_no);
create index if not exists product_alien_terms_thread_idx on public.product_alien_terms (page_id, thread_id, created_at desc);
create index if not exists product_alien_terms_status_idx on public.product_alien_terms (mapping_status, created_at desc);
create index if not exists product_alien_terms_alias_norm_idx on public.product_alien_terms (alias_norm);
create index if not exists product_alien_reviews_status_idx on public.product_alien_map_reviews (mapping_status, created_at desc);

comment on table public.product_alien_terms is 'Raw product words and order evidence; one row per observed product line. Keep raw_text and alias_text unchanged.';
comment on table public.product_alien_map_reviews is 'Review queue for mapping conflicts. Does not write product_master or product_map_master.';
comment on column public.product_alien_terms.raw_text is 'Highest-priority source evidence. Never replace with a mapped display.';
comment on column public.product_alien_terms.alias_text is 'Full alias payload including color, brand, separators, and quantity suffix. Never truncate.';
comment on column public.product_alien_terms.quantity_from_alias is 'Quantity kept from alias/raw text for review; do not trust legacy quantity columns blindly.';
comment on column public.product_alien_map_reviews.master_display_for_packer is 'Read-through value from the existing mapping/master view; never generated by the web UI.';
