-- Alien Room tables for ST SINGTO STORE.
-- This creates evidence/review queues only. It does not modify Product Master or Inventory.
begin;
create table if not exists public.product_alien_terms (
  id bigint generated by default as identity primary key,
  upsert_key text, order_number text, page_id text, page_name text,
  thread_id text, message_id text, line_no integer,
  raw_text text not null default '', raw_text_full text,
  alias_text text, alias_norm text, alias_tokens text,
  alias_quantity_text text, quantity_from_alias text,
  quantity_source text not null default 'ALIAS_TEXT',
  source text not null default 'CAPTURED_FROM_ORDER', source_logic text,
  product_id text, sku text, quantity text, qty text, extracted_qty text, unit text,
  mapping_status text not null default 'REVIEW', review_reason text,
  normalized_chat_timeline jsonb, master_display_for_packer text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.product_alien_map_reviews (
  id bigint generated by default as identity primary key,
  alien_term_id bigint references public.product_alien_terms(id) on delete cascade,
  upsert_key text, order_number text, page_id text, page_name text, thread_id text,
  raw_text text not null default '', alias_text text, alias_norm text,
  quantity_from_alias text, observed_sku text, observed_product_id text,
  observed_quantity text, master_display_for_packer text,
  mapping_status text not null default 'REVIEW', review_reason text,
  reviewer_note text, reviewed_by text, reviewed_at timestamptz,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists product_alien_terms_st_order_idx on public.product_alien_terms (order_number, line_no);
create index if not exists product_alien_terms_st_status_idx on public.product_alien_terms (mapping_status, created_at desc);
create index if not exists product_alien_reviews_st_status_idx on public.product_alien_map_reviews (mapping_status, created_at desc);
commit;

-- Apply only if the web client uses the anon/authenticated key to read these queues.
-- Prefer service_role or a restricted authenticated role in production.
-- grant select, insert, update on public.product_alien_terms to authenticated;
-- grant select, insert, update on public.product_alien_map_reviews to authenticated;
