-- INVENTORY ONE-SHOT SETUP
-- รันก้อนนี้ใน Supabase SQL Editor ของ BB หรือ ST ทีละโปรเจกต์
-- สร้าง inventory + คอลัมน์ + index + RLS/Policy + PostgREST reload
-- รันซ้ำได้ และไม่ลบข้อมูลเดิม

begin;

create table if not exists public.inventory (
  id bigint generated by default as identity primary key,
  product_id bigint,
  sku text,
  stock_qty numeric not null default 0,
  stock_status text not null default 'OUT_OF_STOCK',
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.inventory
  add column if not exists product_id bigint,
  add column if not exists sku text,
  add column if not exists stock_qty numeric not null default 0,
  add column if not exists stock_status text not null default 'OUT_OF_STOCK',
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists created_at timestamptz not null default now();

-- ป้องกันค่าติดลบและทำให้สถานะสอดคล้องกับจำนวน
update public.inventory
set stock_qty = greatest(coalesce(stock_qty, 0), 0),
    stock_status = case
      when greatest(coalesce(stock_qty, 0), 0) > 0 then 'IN_STOCK'
      else 'OUT_OF_STOCK'
    end,
    updated_at = coalesce(updated_at, now());

alter table public.inventory
  drop constraint if exists inventory_stock_qty_nonnegative;

alter table public.inventory
  add constraint inventory_stock_qty_nonnegative
  check (stock_qty >= 0);

alter table public.inventory
  drop constraint if exists inventory_stock_status_check;

alter table public.inventory
  add constraint inventory_stock_status_check
  check (stock_status in ('IN_STOCK', 'OUT_OF_STOCK'));

create index if not exists inventory_product_id_idx
  on public.inventory (product_id);

create index if not exists inventory_sku_upper_idx
  on public.inventory (upper(sku));

create index if not exists inventory_status_idx
  on public.inventory (stock_status, updated_at desc);

-- เปิด Row Level Security สำหรับการเชื่อมต่อจาก browser
alter table public.inventory enable row level security;

-- ทำให้รันซ้ำได้โดยไม่เกิด policy ซ้ำ
 drop policy if exists inventory_browser_select on public.inventory;
 drop policy if exists inventory_browser_insert on public.inventory;
 drop policy if exists inventory_browser_update on public.inventory;

-- สิทธิ์พื้นฐานสำหรับเว็บภายในที่ใช้ Supabase anon key
-- หมายเหตุ: policy นี้ให้ browser ที่ถือ anon key อ่าน/เพิ่ม/แก้ inventory ได้
create policy inventory_browser_select
  on public.inventory
  for select
  to anon, authenticated
  using (true);

create policy inventory_browser_insert
  on public.inventory
  for insert
  to anon, authenticated
  with check (
    stock_qty >= 0
    and stock_status in ('IN_STOCK', 'OUT_OF_STOCK')
  );

create policy inventory_browser_update
  on public.inventory
  for update
  to anon, authenticated
  using (true)
  with check (
    stock_qty >= 0
    and stock_status in ('IN_STOCK', 'OUT_OF_STOCK')
  );

commit;

-- ให้ PostgREST เห็นตาราง/คอลัมน์/Policy ทันที
notify pgrst, 'reload schema';

-- ตรวจผลหลังรัน
select
  c.column_name,
  c.data_type,
  c.is_nullable
from information_schema.columns c
where c.table_schema = 'public'
  and c.table_name = 'inventory'
order by c.ordinal_position;

select
  schemaname,
  tablename,
  rowsecurity
from pg_tables
where schemaname = 'public'
  and tablename = 'inventory';

select
  policyname,
  cmd,
  roles
from pg_policies
where schemaname = 'public'
  and tablename = 'inventory'
order by policyname;

select count(*) as inventory_rows
from public.inventory;
