-- ST ONLY · STOCK STATUS + SENT HISTORY + RECALL
-- Run in the ST Supabase project only.

ALTER TABLE public.product_master
  ADD COLUMN IF NOT EXISTS out_of_stock_joke text,
  ADD COLUMN IF NOT EXISTS stock_notice text;

CREATE OR REPLACE FUNCTION public.refresh_product_stock_notice()
RETURNS trigger LANGUAGE plpgsql AS $function$
BEGIN
  IF COALESCE(NEW.stock_qty, 0) > 0 THEN
    NEW.stock_status := '✅ INSTOCK';
    NEW.status := 'ACTIVE';
    NEW.stock_notice := '✅ มีสินค้า';
  ELSE
    NEW.stock_qty := 0;
    NEW.stock_status := '❌ OUT_OF_STOCK';
    NEW.status := 'OUT_OF_STOCK';
    NEW.stock_notice := COALESCE(NULLIF(BTRIM(NEW.out_of_stock_joke), ''), '❌ สินค้าหมด');
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_product_stock_notice ON public.product_master;
CREATE TRIGGER trg_product_stock_notice
BEFORE INSERT OR UPDATE OF stock_qty, out_of_stock_joke ON public.product_master
FOR EACH ROW EXECUTE FUNCTION public.refresh_product_stock_notice();

UPDATE public.product_master SET stock_qty = COALESCE(stock_qty, 0);

ALTER TABLE public.st_orders
  ADD COLUMN IF NOT EXISTS telegram_status text,
  ADD COLUMN IF NOT EXISTS delivery_state text NOT NULL DEFAULT 'WAITING',
  ADD COLUMN IF NOT EXISTS sent_at timestamptz,
  ADD COLUMN IF NOT EXISTS recalled_at timestamptz,
  ADD COLUMN IF NOT EXISTS recall_count integer NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_delivery_note text;

CREATE TABLE IF NOT EXISTS public.st_orders_sent_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_key text,
  order_number text,
  sent_at timestamptz NOT NULL DEFAULT now(),
  recalled_at timestamptz,
  recall_count integer NOT NULL DEFAULT 0,
  delivery_status text NOT NULL DEFAULT 'SENT',
  snapshot jsonb NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_st_sent_history_key ON public.st_orders_sent_history (order_key, sent_at DESC);

CREATE OR REPLACE FUNCTION public.st_record_sent_history()
RETURNS trigger LANGUAGE plpgsql AS $function$
BEGIN
  IF NEW.telegram_sent IS DISTINCT FROM OLD.telegram_sent
     AND lower(COALESCE(NEW.telegram_sent, '')) IN ('true','1','t','sent','delivered','ไปแล้วไปลับ') THEN
    NEW.delivery_state := 'SENT';
    NEW.sent_at := COALESCE(NEW.sent_at, now());
    INSERT INTO public.st_orders_sent_history(order_key, order_number, sent_at, snapshot)
    VALUES (NEW.upsert_key, NEW.order_number, NEW.sent_at, to_jsonb(NEW));
  END IF;
  RETURN NEW;
END;
$function$;
DROP TRIGGER IF EXISTS trg_st_record_sent_history ON public.st_orders;
CREATE TRIGGER trg_st_record_sent_history BEFORE UPDATE OF telegram_sent ON public.st_orders
FOR EACH ROW EXECUTE FUNCTION public.st_record_sent_history();

CREATE OR REPLACE FUNCTION public.st_recall_order(p_upsert_key text, p_note text DEFAULT 'เรียกกลับจากหน้าเว็บ')
RETURNS public.st_orders LANGUAGE plpgsql SECURITY INVOKER AS $function$
DECLARE result public.st_orders;
BEGIN
  UPDATE public.st_orders
  SET telegram_sent = 'false', telegram_status = 'RECALLED', delivery_state = 'RECALLED', recalled_at = now(), recall_count = COALESCE(recall_count,0) + 1, last_delivery_note = p_note
  WHERE upsert_key = p_upsert_key
  RETURNING * INTO result;
  IF result.upsert_key IS NULL THEN RAISE EXCEPTION 'ไม่พบ ST upsert_key %', p_upsert_key; END IF;
  UPDATE public.st_orders_sent_history SET delivery_status = 'RECALLED', recalled_at = now(), recall_count = result.recall_count WHERE order_key = p_upsert_key AND delivery_status = 'SENT';
  RETURN result;
END;
$function$;
