-- ST ONLY · REMOVE LEGACY TIGER SAFELY
-- This removes only triggers that call fn_holy_trinity_repair_and_sync.
-- It does not delete orders, evidence, or product data.

BEGIN;

CREATE TABLE IF NOT EXISTS public.legacy_tiger_function_backup (
  id bigint generated by default as identity primary key,
  function_oid oid,
  function_signature text,
  function_definition text not null,
  backed_up_at timestamptz not null default now()
);

INSERT INTO public.legacy_tiger_function_backup (
  function_oid,
  function_signature,
  function_definition
)
SELECT
  p.oid,
  format('%I.%I(%s)', n.nspname, p.proname, pg_get_function_identity_arguments(p.oid)),
  pg_get_functiondef(p.oid)
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname = 'public'
  AND p.proname = 'fn_holy_trinity_repair_and_sync'
  AND NOT EXISTS (
    SELECT 1
    FROM public.legacy_tiger_function_backup b
    WHERE b.function_oid = p.oid
  );

DO $block$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT
      t.tgname,
      t.tgrelid::regclass AS table_name
    FROM pg_trigger t
    JOIN pg_proc p ON p.oid = t.tgfoid
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE NOT t.tgisinternal
      AND n.nspname = 'public'
      AND p.proname = 'fn_holy_trinity_repair_and_sync'
  LOOP
    EXECUTE format('DROP TRIGGER IF EXISTS %I ON %s', r.tgname, r.table_name);
  END LOOP;
END
$block$;

DO $block$
DECLARE
  r record;
BEGIN
  FOR r IN
    SELECT
      n.nspname AS schema_name,
      p.proname AS function_name,
      pg_get_function_identity_arguments(p.oid) AS identity_args
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND p.proname = 'fn_holy_trinity_repair_and_sync'
  LOOP
    EXECUTE format('DROP FUNCTION IF EXISTS %I.%I(%s)', r.schema_name, r.function_name, r.identity_args);
  END LOOP;
END
$block$;

COMMIT;

-- Verify: this should return zero rows.
SELECT
  t.tgname,
  t.tgrelid::regclass AS table_name,
  p.proname AS function_name
FROM pg_trigger t
JOIN pg_proc p ON p.oid = t.tgfoid
WHERE NOT t.tgisinternal
  AND p.proname = 'fn_holy_trinity_repair_and_sync';
